### ISSUE TITLE
Failing icicle-fuzzing x86 tests

### ISSUE THREAD

**Issue by ekilmer** [icicle-emu/icicle-emu#35]
Hello! I am seeing test failures related to x86 in the `icicle-fuzzing` package.

```txt
failures:

---- instrumentation::cmp_finder::test::x86_cmov stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmov' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- instrumentation::cmp_finder::test::x86_cmp_jg_const stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmp_jg_const' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_after_sxt stdout ----
thread 'instrumentation::cmp_finder::test::x86_after_sxt' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_cmov_const stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmov_const' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_after_zxt stdout ----
thread 'instrumentation::cmp_finder::test::x86_after_zxt' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_cmp_jl_const stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmp_jl_const' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_cmp_jz stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmp_jz' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_cmp_jz_const stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmp_jz_const' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_cmp_with_mem stdout ----
thread 'instrumentation::cmp_finder::test::x86_cmp_with_mem' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_imul stdout ----
thread 'instrumentation::cmp_finder::test::x86_imul' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_with_extra_instructions stdout ----
thread 'instrumentation::cmp_finder::test::x86_with_extra_instructions' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

---- instrumentation::cmp_finder::test::x86_sub stdout ----
thread 'instrumentation::cmp_finder::test::x86_sub' panicked at 'index out of bounds: the len is 0 but the index is 0', icicle-vm/src/builder.rs:449:33

failures:
    instrumentation::cmp_finder::test::x86_after_sxt
    instrumentation::cmp_finder::test::x86_after_zxt
    instrumentation::cmp_finder::test::x86_cmov
    instrumentation::cmp_finder::test::x86_cmov_const
    instrumentation::cmp_finder::test::x86_cmp_jg_const
    instrumentation::cmp_finder::test::x86_cmp_jl_const
    instrumentation::cmp_finder::test::x86_cmp_jz
    instrumentation::cmp_finder::test::x86_cmp_jz_const
    instrumentation::cmp_finder::test::x86_cmp_with_mem
    instrumentation::cmp_finder::test::x86_imul
    instrumentation::cmp_finder::test::x86_sub
    instrumentation::cmp_finder::test::x86_with_extra_instructions

test result: FAILED. 20 passed; 12 failed; 2 ignored; 0 measured; 0 filtered out; finished in 2.76s
```

To reproduce, I am on commit 17c1f38c3f9baf0fa1afa2626bd4d9743f041561 of this repo, and I have also cloned https://github.com/icicle-emu/ghidra and am using commit 69543445d4d53ae652035f518dc9c3852a14f2dd (latest on `fixes` branch).

I set `GHIDRA_SRC` environment variable to point at the Ghidra checkout and run
```sh
cargo test -p icicle-fuzzing
```

After a little investigation, I believe these failures are caused by the removal of the context vector entries in this commit https://github.com/icicle-emu/icicle-emu/commit/2706b71b0275b0ceae2aa0ee9b83aef1866213b4#diff-7e966a2c1ccd7707fbc8e832898b44f5dde873a167dd0c26031dcabd0a882f6bL328-R416

Adding those values back fixes the tests, but I'm not sure what an alternative looks like, considering they were removed in the first place.

**Comment by mchesser** [comment]
Thanks -- those values are now meant to be loaded from the `.pspec` file (i.e.: https://github.com/icicle-emu/ghidra/blob/fixes/Ghidra/Processors/x86/data/languages/x86-64.pspec#L10-L16), which helps us be compatible with different versions of the sleigh specification.

Normally this is loaded during the Vm build step, however, those tests skip that step.
